CREATE DATABASE PII_Problema1_3_Banco
GO
USE PII_Problema1_3_Banco
GO

CREATE TABLE CLIENTES
(
COD_CLIENTE INT IDENTITY (1,1),
NOMBRE VARCHAR(50),
APELLIDO VARCHAR (50),
DNI INT,

CONSTRAINT PK_CLIENTES PRIMARY KEY (COD_CLIENTE)
)

CREATE TABLE TIPOS_CUENTA
(
COD_TIPO_CUENTA INT IDENTITY (1,1),
NOMBRE VARCHAR(20)

CONSTRAINT PK_TIPOS_CUENTA PRIMARY KEY (COD_TIPO_CUENTA)
)

CREATE TABLE CUENTAS
(
CBU INT,
SALDO DECIMAL(8,2),
COD_TIPO_CUENTA INT,
ULTIMO_MOVIMIENTO DECIMAL(8,2)

CONSTRAINT PK_CUENTAS PRIMARY KEY (CBU),

CONSTRAINT FK_CUENTAS_CLIENTE FOREIGN KEY (COD_TIPO_CUENTA)
REFERENCES TIPOS_CUENTA (COD_TIPO_CUENTA)
)


CREATE TABLE CUENTAS_CLIENTES
(
CBU INT,
COD_CLIENTE INT,


CONSTRAINT PK_CUENTAS_CLIENTES PRIMARY KEY (CBU),

CONSTRAINT FK_CUENTAS_CLIENTES_CUENTAS FOREIGN KEY (CBU)
REFERENCES CUENTAS (CBU),

CONSTRAINT FK_CUENTAS_CLIENTES_CLIENTES FOREIGN KEY (COD_CLIENTE)
REFERENCES CLIENTES (COD_CLIENTE)
)




GO
INSERT INTO TIPOS_CUENTA (NOMBRE) VALUES ('CAJA DE AHORRO')
INSERT INTO TIPOS_CUENTA (NOMBRE) VALUES ('CUENTA CORRIENTE')
INSERT INTO CLIENTES (APELLIDO,NOMBRE,DNI) VALUES ('MAZZAGLIA', 'NICOLAS', 34508327)
INSERT INTO CLIENTES (APELLIDO,NOMBRE,DNI) VALUES ('PEREZ', 'JUAN', 25698789)

GO
CREATE PROCEDURE SP_TipoCuenta
AS
SELECT * FROM TIPOS_CUENTA

select @@VERSION

GO
CREATE PROCEDURE SP_LstClientes
AS
SELECT * FROM CLIENTES
